services:
  php-app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_HOST: mysql-db
    ports:
      - "8081:8081"
    networks:
      - quasi-forum-net
    depends_on:
      - mysql-db
  mysql-db:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - quasi-forum-net
networks:
  quasi-forum-net:
volumes:
  mysql-data:
